#ifndef StMiniMcTree_h
#define StMiniMcTree_h

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>
#include <TCollection.h>
#include "TString.h"
using namespace std;

   const Int_t kMaxmMcTracks = 6000;
   const Int_t kMaxmMatchedPairs = 6000;
   const Int_t kMaxmMergedPairs = 500;
   const Int_t kMaxmSplitPairs = 500;
   const Int_t kMaxmGhostPairs = 1000;
   const Int_t kMaxmContamPairs = 500;
   const Int_t kMaxmMatGlobPairs = 6000;

    //class StRefMultCorr;

class StMiniMcTree {
public :
   TTree          *fChain;   //!pointer to the analyzed TTree or TChain
   Int_t           fCurrent; //!current Tree number in a TChain

   //StRefMultCorr*  refmultCorrUtil; 

   // Declaration of leaf types
   Int_t           mEventId;
   Int_t           mRunId;
   Int_t           mOriginMult;
   Int_t           mCentralMult;
   Int_t           mCentrality;
   Int_t           mNUncorrectedNegativePrimaries;
   Int_t           mNUncorrectedPrimaries;
   Int_t           mNFtpcWUncorrectedPrimaries;
   Int_t           mNFtpcEUncorrectedPrimaries;
   Int_t           mMcMult;
   Int_t           mNMcNch;
   Int_t           mNMcFtpcWNch;
   Int_t           mNMcFtpcENch;
   Int_t           mNMcHminus;
   Int_t           mNMcGlobal;
   Int_t           mNMcGoodGlobal20;
   Int_t           mNRcGlobal;
   Int_t           mNRcGoodGlobal20;
   Float_t         mVertexX;
   Float_t         mVertexY;
   Float_t         mVertexZ;
   Float_t         mVertexCovMatrix[6];
   Float_t         mMcVertexX;
   Float_t         mMcVertexY;
   Float_t         mMcVertexZ;
   Float_t         mMagField;
   Float_t         mCenterOfMassEnergy;
   Float_t         mBackgroundRate;
   Short_t         mBeamMassNumberEast;
   Short_t         mBeamMassNumberWest;
   Float_t         mCtb;
   Float_t         mZdcE;
   Float_t         mZdcW;
   Int_t           mNMcTrack;
   Int_t           mNMatchedPair;
   Int_t           mNMergedPair;
   Int_t           mNSplitPair;
   Int_t           mNGhostPair;
   Int_t           mNContamPair;
   Int_t           mNMatGlobPair;
   Int_t           mMcTracks_;
   Char_t          mMcTracks_mIsValid[kMaxmMcTracks];   //[mMcTracks_]
   Float_t         mMcTracks_mPtMc[kMaxmMcTracks];   //[mMcTracks_]
   Float_t         mMcTracks_mPzMc[kMaxmMcTracks];   //[mMcTracks_]
   Float_t         mMcTracks_mEtaMc[kMaxmMcTracks];   //[mMcTracks_]
   Float_t         mMcTracks_mPhiMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNSvtHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNSsdHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNFtpcHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNBemcHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNBprsHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNBsmdeHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNBsmdpHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNEemcHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNEprsHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNEsmduHitMc[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNEsmdvHitMc[kMaxmMcTracks];   //[mMcTracks_]
   UShort_t        mMcTracks_mGeantId[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mChargeMc[kMaxmMcTracks];   //[mMcTracks_]
   Float_t         mMcTracks_mStopR[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mKey[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mParentKey[kMaxmMcTracks];   //[mMcTracks_]
   UShort_t        mMcTracks_mParentGeantId[kMaxmMcTracks];   //[mMcTracks_]
   Float_t         mMcTracks_mEmcEnergyMcHit[kMaxmMcTracks][3];   //[mMcTracks_]
   Float_t         mMcTracks_mEmcEnergyMcSum[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mEmcSoftIdHiTowerMc[kMaxmMcTracks][3];   //[mMcTracks_]
   Short_t         mMcTracks_mNAssocGl[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mNAssocPr[kMaxmMcTracks];   //[mMcTracks_]
   Short_t         mMcTracks_mIsPrimary[kMaxmMcTracks];   //[mMcTracks_]
   UInt_t          mMcTracks_fUniqueID[kMaxmMcTracks];   //[mMcTracks_]
   UInt_t          mMcTracks_fBits[kMaxmMcTracks];   //[mMcTracks_]
   Int_t           mMatchedPairs_;
   Short_t         mMatchedPairs_mNCommonHit[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mIsBestContam[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mDominatrack[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mDominCommonHit[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mAvgQuality[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Char_t          mMatchedPairs_mIsValid[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPtMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPzMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mEtaMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPhiMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNSvtHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNSsdHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNFtpcHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNBemcHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNBprsHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNBsmdeHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNBsmdpHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNEemcHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNEprsHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNEsmduHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNEsmdvHitMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   UShort_t        mMatchedPairs_mGeantId[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mChargeMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mStopR[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mKey[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mParentKey[kMaxmMatchedPairs];   //[mMatchedPairs_]
   UShort_t        mMatchedPairs_mParentGeantId[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mEmcEnergyMcHit[kMaxmMatchedPairs][3];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mEmcEnergyMcSum[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mEmcSoftIdHiTowerMc[kMaxmMatchedPairs][3];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNAssocGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNAssocPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mIsPrimary[kMaxmMatchedPairs];   //[mMatchedPairs_]
   UInt_t          mMatchedPairs_fUniqueID[kMaxmMatchedPairs];   //[mMatchedPairs_]
   UInt_t          mMatchedPairs_fBits[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Char_t          mMatchedPairs_mIsValidGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPtPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPzPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mEtaPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPhiPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaXYPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaZPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaXYPrMcV[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaZPrMcV[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mCurvPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mTanLPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mErrP[kMaxmMatchedPairs][5];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mChi2Pr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mFlag[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDedx[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPtGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPzGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mEtaGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPhiGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaXYGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaZGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaXYGlMcV[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mDcaZGlMcV[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mCurvGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mTanLGl[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mErrG[kMaxmMatchedPairs][5];   //[mMatchedPairs_]
   UShort_t        mMatchedPairs_mSeedQA[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPidPion[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPidProton[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPidKaon[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mPidElectron[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mFirstZ[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mLastZ[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mFirstPadrow[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mLastPadrow[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mFirstFitPadrow[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mLastFitPadrow[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mFirstSector[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mLastSector[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mRecoKey[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mFitPts[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mFitSvt[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mFitSsd[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mFitFtpc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mDedxPts[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mAllPts[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mCharge[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNAssocMc[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mNPossible[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Char_t          mMatchedPairs_mIsValidPr[kMaxmMatchedPairs];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mEmcTowerAdc[kMaxmMatchedPairs][3];   //[mMatchedPairs_]
   Float_t         mMatchedPairs_mEmcEnergyRcHit[kMaxmMatchedPairs][3];   //[mMatchedPairs_]
   Short_t         mMatchedPairs_mEmcSoftIdHiTowerRc[kMaxmMatchedPairs][3];   //[mMatchedPairs_]
   Int_t           mMergedPairs_;
   Short_t         mMergedPairs_mNCommonHit[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mIsBestContam[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mDominatrack[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mDominCommonHit[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mAvgQuality[kMaxmMergedPairs];   //[mMergedPairs_]
   Char_t          mMergedPairs_mIsValid[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPtMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPzMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mEtaMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPhiMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNSvtHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNSsdHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNFtpcHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNBemcHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNBprsHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNBsmdeHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNBsmdpHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNEemcHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNEprsHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNEsmduHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNEsmdvHitMc[kMaxmMergedPairs];   //[mMergedPairs_]
   UShort_t        mMergedPairs_mGeantId[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mChargeMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mStopR[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mKey[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mParentKey[kMaxmMergedPairs];   //[mMergedPairs_]
   UShort_t        mMergedPairs_mParentGeantId[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mEmcEnergyMcHit[kMaxmMergedPairs][3];   //[mMergedPairs_]
   Float_t         mMergedPairs_mEmcEnergyMcSum[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mEmcSoftIdHiTowerMc[kMaxmMergedPairs][3];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNAssocGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNAssocPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mIsPrimary[kMaxmMergedPairs];   //[mMergedPairs_]
   UInt_t          mMergedPairs_fUniqueID[kMaxmMergedPairs];   //[mMergedPairs_]
   UInt_t          mMergedPairs_fBits[kMaxmMergedPairs];   //[mMergedPairs_]
   Char_t          mMergedPairs_mIsValidGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPtPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPzPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mEtaPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPhiPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaXYPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaZPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaXYPrMcV[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaZPrMcV[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mCurvPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mTanLPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mErrP[kMaxmMergedPairs][5];   //[mMergedPairs_]
   Float_t         mMergedPairs_mChi2Pr[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mFlag[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDedx[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPtGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPzGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mEtaGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPhiGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaXYGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaZGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaXYGlMcV[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mDcaZGlMcV[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mCurvGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mTanLGl[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mErrG[kMaxmMergedPairs][5];   //[mMergedPairs_]
   UShort_t        mMergedPairs_mSeedQA[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPidPion[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPidProton[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPidKaon[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mPidElectron[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mFirstZ[kMaxmMergedPairs];   //[mMergedPairs_]
   Float_t         mMergedPairs_mLastZ[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mFirstPadrow[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mLastPadrow[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mFirstFitPadrow[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mLastFitPadrow[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mFirstSector[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mLastSector[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mRecoKey[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mFitPts[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mFitSvt[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mFitSsd[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mFitFtpc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mDedxPts[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mAllPts[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mCharge[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNAssocMc[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mNPossible[kMaxmMergedPairs];   //[mMergedPairs_]
   Char_t          mMergedPairs_mIsValidPr[kMaxmMergedPairs];   //[mMergedPairs_]
   Short_t         mMergedPairs_mEmcTowerAdc[kMaxmMergedPairs][3];   //[mMergedPairs_]
   Float_t         mMergedPairs_mEmcEnergyRcHit[kMaxmMergedPairs][3];   //[mMergedPairs_]
   Short_t         mMergedPairs_mEmcSoftIdHiTowerRc[kMaxmMergedPairs][3];   //[mMergedPairs_]
   Int_t           mSplitPairs_;
   Short_t         mSplitPairs_mNCommonHit[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mIsBestContam[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mDominatrack[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mDominCommonHit[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mAvgQuality[kMaxmSplitPairs];   //[mSplitPairs_]
   Char_t          mSplitPairs_mIsValid[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPtMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPzMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mEtaMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPhiMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNSvtHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNSsdHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNFtpcHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNBemcHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNBprsHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNBsmdeHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNBsmdpHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNEemcHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNEprsHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNEsmduHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNEsmdvHitMc[kMaxmSplitPairs];   //[mSplitPairs_]
   UShort_t        mSplitPairs_mGeantId[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mChargeMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mStopR[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mKey[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mParentKey[kMaxmSplitPairs];   //[mSplitPairs_]
   UShort_t        mSplitPairs_mParentGeantId[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mEmcEnergyMcHit[kMaxmSplitPairs][3];   //[mSplitPairs_]
   Float_t         mSplitPairs_mEmcEnergyMcSum[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mEmcSoftIdHiTowerMc[kMaxmSplitPairs][3];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNAssocGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNAssocPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mIsPrimary[kMaxmSplitPairs];   //[mSplitPairs_]
   UInt_t          mSplitPairs_fUniqueID[kMaxmSplitPairs];   //[mSplitPairs_]
   UInt_t          mSplitPairs_fBits[kMaxmSplitPairs];   //[mSplitPairs_]
   Char_t          mSplitPairs_mIsValidGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPtPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPzPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mEtaPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPhiPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaXYPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaZPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaXYPrMcV[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaZPrMcV[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mCurvPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mTanLPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mErrP[kMaxmSplitPairs][5];   //[mSplitPairs_]
   Float_t         mSplitPairs_mChi2Pr[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mFlag[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDedx[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPtGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPzGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mEtaGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPhiGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaXYGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaZGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaXYGlMcV[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mDcaZGlMcV[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mCurvGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mTanLGl[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mErrG[kMaxmSplitPairs][5];   //[mSplitPairs_]
   UShort_t        mSplitPairs_mSeedQA[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPidPion[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPidProton[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPidKaon[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mPidElectron[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mFirstZ[kMaxmSplitPairs];   //[mSplitPairs_]
   Float_t         mSplitPairs_mLastZ[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mFirstPadrow[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mLastPadrow[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mFirstFitPadrow[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mLastFitPadrow[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mFirstSector[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mLastSector[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mRecoKey[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mFitPts[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mFitSvt[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mFitSsd[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mFitFtpc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mDedxPts[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mAllPts[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mCharge[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNAssocMc[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mNPossible[kMaxmSplitPairs];   //[mSplitPairs_]
   Char_t          mSplitPairs_mIsValidPr[kMaxmSplitPairs];   //[mSplitPairs_]
   Short_t         mSplitPairs_mEmcTowerAdc[kMaxmSplitPairs][3];   //[mSplitPairs_]
   Float_t         mSplitPairs_mEmcEnergyRcHit[kMaxmSplitPairs][3];   //[mSplitPairs_]
   Short_t         mSplitPairs_mEmcSoftIdHiTowerRc[kMaxmSplitPairs][3];   //[mSplitPairs_]
   Int_t           mGhostPairs_;
   Short_t         mGhostPairs_mNCommonHit[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mIsBestContam[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mDominatrack[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mDominCommonHit[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mAvgQuality[kMaxmGhostPairs];   //[mGhostPairs_]
   Char_t          mGhostPairs_mIsValid[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPtMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPzMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mEtaMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPhiMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNSvtHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNSsdHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNFtpcHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNBemcHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNBprsHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNBsmdeHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNBsmdpHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNEemcHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNEprsHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNEsmduHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNEsmdvHitMc[kMaxmGhostPairs];   //[mGhostPairs_]
   UShort_t        mGhostPairs_mGeantId[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mChargeMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mStopR[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mKey[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mParentKey[kMaxmGhostPairs];   //[mGhostPairs_]
   UShort_t        mGhostPairs_mParentGeantId[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mEmcEnergyMcHit[kMaxmGhostPairs][3];   //[mGhostPairs_]
   Float_t         mGhostPairs_mEmcEnergyMcSum[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mEmcSoftIdHiTowerMc[kMaxmGhostPairs][3];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNAssocGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNAssocPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mIsPrimary[kMaxmGhostPairs];   //[mGhostPairs_]
   UInt_t          mGhostPairs_fUniqueID[kMaxmGhostPairs];   //[mGhostPairs_]
   UInt_t          mGhostPairs_fBits[kMaxmGhostPairs];   //[mGhostPairs_]
   Char_t          mGhostPairs_mIsValidGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPtPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPzPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mEtaPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPhiPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaXYPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaZPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaXYPrMcV[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaZPrMcV[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mCurvPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mTanLPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mErrP[kMaxmGhostPairs][5];   //[mGhostPairs_]
   Float_t         mGhostPairs_mChi2Pr[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mFlag[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDedx[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPtGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPzGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mEtaGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPhiGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaXYGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaZGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaXYGlMcV[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mDcaZGlMcV[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mCurvGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mTanLGl[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mErrG[kMaxmGhostPairs][5];   //[mGhostPairs_]
   UShort_t        mGhostPairs_mSeedQA[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPidPion[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPidProton[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPidKaon[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mPidElectron[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mFirstZ[kMaxmGhostPairs];   //[mGhostPairs_]
   Float_t         mGhostPairs_mLastZ[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mFirstPadrow[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mLastPadrow[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mFirstFitPadrow[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mLastFitPadrow[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mFirstSector[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mLastSector[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mRecoKey[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mFitPts[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mFitSvt[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mFitSsd[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mFitFtpc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mDedxPts[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mAllPts[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mCharge[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNAssocMc[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mNPossible[kMaxmGhostPairs];   //[mGhostPairs_]
   Char_t          mGhostPairs_mIsValidPr[kMaxmGhostPairs];   //[mGhostPairs_]
   Short_t         mGhostPairs_mEmcTowerAdc[kMaxmGhostPairs][3];   //[mGhostPairs_]
   Float_t         mGhostPairs_mEmcEnergyRcHit[kMaxmGhostPairs][3];   //[mGhostPairs_]
   Short_t         mGhostPairs_mEmcSoftIdHiTowerRc[kMaxmGhostPairs][3];   //[mGhostPairs_]
   Int_t           mContamPairs_;
   Int_t           mContamPairs_mParentGeantId[kMaxmContamPairs];   //[mContamPairs_]
   Int_t           mContamPairs_mGeantProcess[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPtMcParent[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mEtaMcParent[kMaxmContamPairs];   //[mContamPairs_]
   Int_t           mContamPairs_mParentParentGeantId[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPtMcParentParent[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mStartX[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mStartY[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mStartZ[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNCommonHit[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mIsBestContam[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mDominatrack[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mDominCommonHit[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mAvgQuality[kMaxmContamPairs];   //[mContamPairs_]
   Char_t          mContamPairs_mIsValid[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPtMc[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPzMc[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mEtaMc[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPhiMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNSvtHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNSsdHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNFtpcHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNBemcHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNBprsHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNBsmdeHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNBsmdpHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNEemcHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNEprsHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNEsmduHitMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNEsmdvHitMc[kMaxmContamPairs];   //[mContamPairs_]
   UShort_t        mContamPairs_mGeantId[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mChargeMc[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mStopR[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mKey[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mParentKey[kMaxmContamPairs];   //[mContamPairs_]
   //UShort_t        mContamPairs_mParentGeantId[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mEmcEnergyMcHit[kMaxmContamPairs][3];   //[mContamPairs_]
   Float_t         mContamPairs_mEmcEnergyMcSum[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mEmcSoftIdHiTowerMc[kMaxmContamPairs][3];   //[mContamPairs_]
   Short_t         mContamPairs_mNAssocGl[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNAssocPr[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mIsPrimary[kMaxmContamPairs];   //[mContamPairs_]
   UInt_t          mContamPairs_fUniqueID[kMaxmContamPairs];   //[mContamPairs_]
   UInt_t          mContamPairs_fBits[kMaxmContamPairs];   //[mContamPairs_]
   Char_t          mContamPairs_mIsValidGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPtPr[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPzPr[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mEtaPr[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPhiPr[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaPr[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaXYPr[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaZPr[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaXYPrMcV[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaZPrMcV[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mCurvPr[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mTanLPr[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mErrP[kMaxmContamPairs][5];   //[mContamPairs_]
   Float_t         mContamPairs_mChi2Pr[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mFlag[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDedx[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPtGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPzGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mEtaGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPhiGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaXYGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaZGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaXYGlMcV[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mDcaZGlMcV[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mCurvGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mTanLGl[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mErrG[kMaxmContamPairs][5];   //[mContamPairs_]
   UShort_t        mContamPairs_mSeedQA[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPidPion[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPidProton[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPidKaon[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mPidElectron[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mFirstZ[kMaxmContamPairs];   //[mContamPairs_]
   Float_t         mContamPairs_mLastZ[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mFirstPadrow[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mLastPadrow[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mFirstFitPadrow[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mLastFitPadrow[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mFirstSector[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mLastSector[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mRecoKey[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mFitPts[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mFitSvt[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mFitSsd[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mFitFtpc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mDedxPts[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mAllPts[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mCharge[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNAssocMc[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mNPossible[kMaxmContamPairs];   //[mContamPairs_]
   Char_t          mContamPairs_mIsValidPr[kMaxmContamPairs];   //[mContamPairs_]
   Short_t         mContamPairs_mEmcTowerAdc[kMaxmContamPairs][3];   //[mContamPairs_]
   Float_t         mContamPairs_mEmcEnergyRcHit[kMaxmContamPairs][3];   //[mContamPairs_]
   Short_t         mContamPairs_mEmcSoftIdHiTowerRc[kMaxmContamPairs][3];   //[mContamPairs_]
   Int_t           mMatGlobPairs_;
   Short_t         mMatGlobPairs_mNCommonHit[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mIsBestContam[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mDominatrack[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mDominCommonHit[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mAvgQuality[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Char_t          mMatGlobPairs_mIsValid[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPtMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPzMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mEtaMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPhiMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNSvtHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNSsdHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNFtpcHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNBemcHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNBprsHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNBsmdeHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNBsmdpHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNEemcHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNEprsHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNEsmduHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNEsmdvHitMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   UShort_t        mMatGlobPairs_mGeantId[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mChargeMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mStopR[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mKey[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mParentKey[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   UShort_t        mMatGlobPairs_mParentGeantId[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mEmcEnergyMcHit[kMaxmMatGlobPairs][3];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mEmcEnergyMcSum[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mEmcSoftIdHiTowerMc[kMaxmMatGlobPairs][3];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNAssocGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNAssocPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mIsPrimary[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   UInt_t          mMatGlobPairs_fUniqueID[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   UInt_t          mMatGlobPairs_fBits[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Char_t          mMatGlobPairs_mIsValidGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPtPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPzPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mEtaPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPhiPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaXYPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaZPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaXYPrMcV[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaZPrMcV[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mCurvPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mTanLPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mErrP[kMaxmMatGlobPairs][5];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mChi2Pr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mFlag[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDedx[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPtGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPzGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mEtaGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPhiGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaXYGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaZGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaXYGlMcV[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mDcaZGlMcV[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mCurvGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mTanLGl[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mErrG[kMaxmMatGlobPairs][5];   //[mMatGlobPairs_]
   UShort_t        mMatGlobPairs_mSeedQA[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPidPion[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPidProton[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPidKaon[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mPidElectron[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mFirstZ[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mLastZ[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mFirstPadrow[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mLastPadrow[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mFirstFitPadrow[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mLastFitPadrow[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mFirstSector[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mLastSector[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mRecoKey[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mFitPts[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mFitSvt[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mFitSsd[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mFitFtpc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mDedxPts[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mAllPts[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mCharge[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNAssocMc[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mNPossible[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Char_t          mMatGlobPairs_mIsValidPr[kMaxmMatGlobPairs];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mEmcTowerAdc[kMaxmMatGlobPairs][3];   //[mMatGlobPairs_]
   Float_t         mMatGlobPairs_mEmcEnergyRcHit[kMaxmMatGlobPairs][3];   //[mMatGlobPairs_]
   Short_t         mMatGlobPairs_mEmcSoftIdHiTowerRc[kMaxmMatGlobPairs][3];   //[mMatGlobPairs_]
   UInt_t          fUniqueID;
   UInt_t          fBits;

   // List of branches
   TBranch        *b_StMiniMcEvent_mEventId;   //!
   TBranch        *b_StMiniMcEvent_mRunId;   //!
   TBranch        *b_StMiniMcEvent_mOriginMult;   //!
   TBranch        *b_StMiniMcEvent_mCentralMult;   //!
   TBranch        *b_StMiniMcEvent_mCentrality;   //!
   TBranch        *b_StMiniMcEvent_mNUncorrectedNegativePrimaries;   //!
   TBranch        *b_StMiniMcEvent_mNUncorrectedPrimaries;   //!
   TBranch        *b_StMiniMcEvent_mNFtpcWUncorrectedPrimaries;   //!
   TBranch        *b_StMiniMcEvent_mNFtpcEUncorrectedPrimaries;   //!
   TBranch        *b_StMiniMcEvent_mMcMult;   //!
   TBranch        *b_StMiniMcEvent_mNMcNch;   //!
   TBranch        *b_StMiniMcEvent_mNMcFtpcWNch;   //!
   TBranch        *b_StMiniMcEvent_mNMcFtpcENch;   //!
   TBranch        *b_StMiniMcEvent_mNMcHminus;   //!
   TBranch        *b_StMiniMcEvent_mNMcGlobal;   //!
   TBranch        *b_StMiniMcEvent_mNMcGoodGlobal20;   //!
   TBranch        *b_StMiniMcEvent_mNRcGlobal;   //!
   TBranch        *b_StMiniMcEvent_mNRcGoodGlobal20;   //!
   TBranch        *b_StMiniMcEvent_mVertexX;   //!
   TBranch        *b_StMiniMcEvent_mVertexY;   //!
   TBranch        *b_StMiniMcEvent_mVertexZ;   //!
   TBranch        *b_StMiniMcEvent_mVertexCovMatrix;   //!
   TBranch        *b_StMiniMcEvent_mMcVertexX;   //!
   TBranch        *b_StMiniMcEvent_mMcVertexY;   //!
   TBranch        *b_StMiniMcEvent_mMcVertexZ;   //!
   TBranch        *b_StMiniMcEvent_mMagField;   //!
   TBranch        *b_StMiniMcEvent_mCenterOfMassEnergy;   //!
   TBranch        *b_StMiniMcEvent_mBackgroundRate;   //!
   TBranch        *b_StMiniMcEvent_mBeamMassNumberEast;   //!
   TBranch        *b_StMiniMcEvent_mBeamMassNumberWest;   //!
   TBranch        *b_StMiniMcEvent_mCtb;   //!
   TBranch        *b_StMiniMcEvent_mZdcE;   //!
   TBranch        *b_StMiniMcEvent_mZdcW;   //!
   TBranch        *b_StMiniMcEvent_mNMcTrack;   //!
   TBranch        *b_StMiniMcEvent_mNMatchedPair;   //!
   TBranch        *b_StMiniMcEvent_mNMergedPair;   //!
   TBranch        *b_StMiniMcEvent_mNSplitPair;   //!
   TBranch        *b_StMiniMcEvent_mNGhostPair;   //!
   TBranch        *b_StMiniMcEvent_mNContamPair;   //!
   TBranch        *b_StMiniMcEvent_mNMatGlobPair;   //!
   TBranch        *b_mMcTracks_;   //!
   TBranch        *b_mMcTracks_mIsValid;   //!
   TBranch        *b_mMcTracks_mPtMc;   //!
   TBranch        *b_mMcTracks_mPzMc;   //!
   TBranch        *b_mMcTracks_mEtaMc;   //!
   TBranch        *b_mMcTracks_mPhiMc;   //!
   TBranch        *b_mMcTracks_mNHitMc;   //!
   TBranch        *b_mMcTracks_mNSvtHitMc;   //!
   TBranch        *b_mMcTracks_mNSsdHitMc;   //!
   TBranch        *b_mMcTracks_mNFtpcHitMc;   //!
   TBranch        *b_mMcTracks_mNBemcHitMc;   //!
   TBranch        *b_mMcTracks_mNBprsHitMc;   //!
   TBranch        *b_mMcTracks_mNBsmdeHitMc;   //!
   TBranch        *b_mMcTracks_mNBsmdpHitMc;   //!
   TBranch        *b_mMcTracks_mNEemcHitMc;   //!
   TBranch        *b_mMcTracks_mNEprsHitMc;   //!
   TBranch        *b_mMcTracks_mNEsmduHitMc;   //!
   TBranch        *b_mMcTracks_mNEsmdvHitMc;   //!
   TBranch        *b_mMcTracks_mGeantId;   //!
   TBranch        *b_mMcTracks_mChargeMc;   //!
   TBranch        *b_mMcTracks_mStopR;   //!
   TBranch        *b_mMcTracks_mKey;   //!
   TBranch        *b_mMcTracks_mParentKey;   //!
   TBranch        *b_mMcTracks_mParentGeantId;   //!
   TBranch        *b_mMcTracks_mEmcEnergyMcHit;   //!
   TBranch        *b_mMcTracks_mEmcEnergyMcSum;   //!
   TBranch        *b_mMcTracks_mEmcSoftIdHiTowerMc;   //!
   TBranch        *b_mMcTracks_mNAssocGl;   //!
   TBranch        *b_mMcTracks_mNAssocPr;   //!
   TBranch        *b_mMcTracks_mIsPrimary;   //!
   TBranch        *b_mMcTracks_fUniqueID;   //!
   TBranch        *b_mMcTracks_fBits;   //!
   TBranch        *b_mMatchedPairs_;   //!
   TBranch        *b_mMatchedPairs_mNCommonHit;   //!
   TBranch        *b_mMatchedPairs_mIsBestContam;   //!
   TBranch        *b_mMatchedPairs_mDominatrack;   //!
   TBranch        *b_mMatchedPairs_mDominCommonHit;   //!
   TBranch        *b_mMatchedPairs_mAvgQuality;   //!
   TBranch        *b_mMatchedPairs_mIsValid;   //!
   TBranch        *b_mMatchedPairs_mPtMc;   //!
   TBranch        *b_mMatchedPairs_mPzMc;   //!
   TBranch        *b_mMatchedPairs_mEtaMc;   //!
   TBranch        *b_mMatchedPairs_mPhiMc;   //!
   TBranch        *b_mMatchedPairs_mNHitMc;   //!
   TBranch        *b_mMatchedPairs_mNSvtHitMc;   //!
   TBranch        *b_mMatchedPairs_mNSsdHitMc;   //!
   TBranch        *b_mMatchedPairs_mNFtpcHitMc;   //!
   TBranch        *b_mMatchedPairs_mNBemcHitMc;   //!
   TBranch        *b_mMatchedPairs_mNBprsHitMc;   //!
   TBranch        *b_mMatchedPairs_mNBsmdeHitMc;   //!
   TBranch        *b_mMatchedPairs_mNBsmdpHitMc;   //!
   TBranch        *b_mMatchedPairs_mNEemcHitMc;   //!
   TBranch        *b_mMatchedPairs_mNEprsHitMc;   //!
   TBranch        *b_mMatchedPairs_mNEsmduHitMc;   //!
   TBranch        *b_mMatchedPairs_mNEsmdvHitMc;   //!
   TBranch        *b_mMatchedPairs_mGeantId;   //!
   TBranch        *b_mMatchedPairs_mChargeMc;   //!
   TBranch        *b_mMatchedPairs_mStopR;   //!
   TBranch        *b_mMatchedPairs_mKey;   //!
   TBranch        *b_mMatchedPairs_mParentKey;   //!
   TBranch        *b_mMatchedPairs_mParentGeantId;   //!
   TBranch        *b_mMatchedPairs_mEmcEnergyMcHit;   //!
   TBranch        *b_mMatchedPairs_mEmcEnergyMcSum;   //!
   TBranch        *b_mMatchedPairs_mEmcSoftIdHiTowerMc;   //!
   TBranch        *b_mMatchedPairs_mNAssocGl;   //!
   TBranch        *b_mMatchedPairs_mNAssocPr;   //!
   TBranch        *b_mMatchedPairs_mIsPrimary;   //!
   TBranch        *b_mMatchedPairs_fUniqueID;   //!
   TBranch        *b_mMatchedPairs_fBits;   //!
   TBranch        *b_mMatchedPairs_mIsValidGl;   //!
   TBranch        *b_mMatchedPairs_mPtPr;   //!
   TBranch        *b_mMatchedPairs_mPzPr;   //!
   TBranch        *b_mMatchedPairs_mEtaPr;   //!
   TBranch        *b_mMatchedPairs_mPhiPr;   //!
   TBranch        *b_mMatchedPairs_mDcaPr;   //!
   TBranch        *b_mMatchedPairs_mDcaXYPr;   //!
   TBranch        *b_mMatchedPairs_mDcaZPr;   //!
   TBranch        *b_mMatchedPairs_mDcaXYPrMcV;   //!
   TBranch        *b_mMatchedPairs_mDcaZPrMcV;   //!
   TBranch        *b_mMatchedPairs_mCurvPr;   //!
   TBranch        *b_mMatchedPairs_mTanLPr;   //!
   TBranch        *b_mMatchedPairs_mErrP;   //!
   TBranch        *b_mMatchedPairs_mChi2Pr;   //!
   TBranch        *b_mMatchedPairs_mFlag;   //!
   TBranch        *b_mMatchedPairs_mDedx;   //!
   TBranch        *b_mMatchedPairs_mPtGl;   //!
   TBranch        *b_mMatchedPairs_mPzGl;   //!
   TBranch        *b_mMatchedPairs_mEtaGl;   //!
   TBranch        *b_mMatchedPairs_mPhiGl;   //!
   TBranch        *b_mMatchedPairs_mDcaGl;   //!
   TBranch        *b_mMatchedPairs_mDcaXYGl;   //!
   TBranch        *b_mMatchedPairs_mDcaZGl;   //!
   TBranch        *b_mMatchedPairs_mDcaXYGlMcV;   //!
   TBranch        *b_mMatchedPairs_mDcaZGlMcV;   //!
   TBranch        *b_mMatchedPairs_mCurvGl;   //!
   TBranch        *b_mMatchedPairs_mTanLGl;   //!
   TBranch        *b_mMatchedPairs_mErrG;   //!
   TBranch        *b_mMatchedPairs_mSeedQA;   //!
   TBranch        *b_mMatchedPairs_mPidPion;   //!
   TBranch        *b_mMatchedPairs_mPidProton;   //!
   TBranch        *b_mMatchedPairs_mPidKaon;   //!
   TBranch        *b_mMatchedPairs_mPidElectron;   //!
   TBranch        *b_mMatchedPairs_mFirstZ;   //!
   TBranch        *b_mMatchedPairs_mLastZ;   //!
   TBranch        *b_mMatchedPairs_mFirstPadrow;   //!
   TBranch        *b_mMatchedPairs_mLastPadrow;   //!
   TBranch        *b_mMatchedPairs_mFirstFitPadrow;   //!
   TBranch        *b_mMatchedPairs_mLastFitPadrow;   //!
   TBranch        *b_mMatchedPairs_mFirstSector;   //!
   TBranch        *b_mMatchedPairs_mLastSector;   //!
   TBranch        *b_mMatchedPairs_mRecoKey;   //!
   TBranch        *b_mMatchedPairs_mFitPts;   //!
   TBranch        *b_mMatchedPairs_mFitSvt;   //!
   TBranch        *b_mMatchedPairs_mFitSsd;   //!
   TBranch        *b_mMatchedPairs_mFitFtpc;   //!
   TBranch        *b_mMatchedPairs_mDedxPts;   //!
   TBranch        *b_mMatchedPairs_mAllPts;   //!
   TBranch        *b_mMatchedPairs_mCharge;   //!
   TBranch        *b_mMatchedPairs_mNAssocMc;   //!
   TBranch        *b_mMatchedPairs_mNPossible;   //!
   TBranch        *b_mMatchedPairs_mIsValidPr;   //!
   TBranch        *b_mMatchedPairs_mEmcTowerAdc;   //!
   TBranch        *b_mMatchedPairs_mEmcEnergyRcHit;   //!
   TBranch        *b_mMatchedPairs_mEmcSoftIdHiTowerRc;   //!
   TBranch        *b_mMergedPairs_;   //!
   TBranch        *b_mMergedPairs_mNCommonHit;   //!
   TBranch        *b_mMergedPairs_mIsBestContam;   //!
   TBranch        *b_mMergedPairs_mDominatrack;   //!
   TBranch        *b_mMergedPairs_mDominCommonHit;   //!
   TBranch        *b_mMergedPairs_mAvgQuality;   //!
   TBranch        *b_mMergedPairs_mIsValid;   //!
   TBranch        *b_mMergedPairs_mPtMc;   //!
   TBranch        *b_mMergedPairs_mPzMc;   //!
   TBranch        *b_mMergedPairs_mEtaMc;   //!
   TBranch        *b_mMergedPairs_mPhiMc;   //!
   TBranch        *b_mMergedPairs_mNHitMc;   //!
   TBranch        *b_mMergedPairs_mNSvtHitMc;   //!
   TBranch        *b_mMergedPairs_mNSsdHitMc;   //!
   TBranch        *b_mMergedPairs_mNFtpcHitMc;   //!
   TBranch        *b_mMergedPairs_mNBemcHitMc;   //!
   TBranch        *b_mMergedPairs_mNBprsHitMc;   //!
   TBranch        *b_mMergedPairs_mNBsmdeHitMc;   //!
   TBranch        *b_mMergedPairs_mNBsmdpHitMc;   //!
   TBranch        *b_mMergedPairs_mNEemcHitMc;   //!
   TBranch        *b_mMergedPairs_mNEprsHitMc;   //!
   TBranch        *b_mMergedPairs_mNEsmduHitMc;   //!
   TBranch        *b_mMergedPairs_mNEsmdvHitMc;   //!
   TBranch        *b_mMergedPairs_mGeantId;   //!
   TBranch        *b_mMergedPairs_mChargeMc;   //!
   TBranch        *b_mMergedPairs_mStopR;   //!
   TBranch        *b_mMergedPairs_mKey;   //!
   TBranch        *b_mMergedPairs_mParentKey;   //!
   TBranch        *b_mMergedPairs_mParentGeantId;   //!
   TBranch        *b_mMergedPairs_mEmcEnergyMcHit;   //!
   TBranch        *b_mMergedPairs_mEmcEnergyMcSum;   //!
   TBranch        *b_mMergedPairs_mEmcSoftIdHiTowerMc;   //!
   TBranch        *b_mMergedPairs_mNAssocGl;   //!
   TBranch        *b_mMergedPairs_mNAssocPr;   //!
   TBranch        *b_mMergedPairs_mIsPrimary;   //!
   TBranch        *b_mMergedPairs_fUniqueID;   //!
   TBranch        *b_mMergedPairs_fBits;   //!
   TBranch        *b_mMergedPairs_mIsValidGl;   //!
   TBranch        *b_mMergedPairs_mPtPr;   //!
   TBranch        *b_mMergedPairs_mPzPr;   //!
   TBranch        *b_mMergedPairs_mEtaPr;   //!
   TBranch        *b_mMergedPairs_mPhiPr;   //!
   TBranch        *b_mMergedPairs_mDcaPr;   //!
   TBranch        *b_mMergedPairs_mDcaXYPr;   //!
   TBranch        *b_mMergedPairs_mDcaZPr;   //!
   TBranch        *b_mMergedPairs_mDcaXYPrMcV;   //!
   TBranch        *b_mMergedPairs_mDcaZPrMcV;   //!
   TBranch        *b_mMergedPairs_mCurvPr;   //!
   TBranch        *b_mMergedPairs_mTanLPr;   //!
   TBranch        *b_mMergedPairs_mErrP;   //!
   TBranch        *b_mMergedPairs_mChi2Pr;   //!
   TBranch        *b_mMergedPairs_mFlag;   //!
   TBranch        *b_mMergedPairs_mDedx;   //!
   TBranch        *b_mMergedPairs_mPtGl;   //!
   TBranch        *b_mMergedPairs_mPzGl;   //!
   TBranch        *b_mMergedPairs_mEtaGl;   //!
   TBranch        *b_mMergedPairs_mPhiGl;   //!
   TBranch        *b_mMergedPairs_mDcaGl;   //!
   TBranch        *b_mMergedPairs_mDcaXYGl;   //!
   TBranch        *b_mMergedPairs_mDcaZGl;   //!
   TBranch        *b_mMergedPairs_mDcaXYGlMcV;   //!
   TBranch        *b_mMergedPairs_mDcaZGlMcV;   //!
   TBranch        *b_mMergedPairs_mCurvGl;   //!
   TBranch        *b_mMergedPairs_mTanLGl;   //!
   TBranch        *b_mMergedPairs_mErrG;   //!
   TBranch        *b_mMergedPairs_mSeedQA;   //!
   TBranch        *b_mMergedPairs_mPidPion;   //!
   TBranch        *b_mMergedPairs_mPidProton;   //!
   TBranch        *b_mMergedPairs_mPidKaon;   //!
   TBranch        *b_mMergedPairs_mPidElectron;   //!
   TBranch        *b_mMergedPairs_mFirstZ;   //!
   TBranch        *b_mMergedPairs_mLastZ;   //!
   TBranch        *b_mMergedPairs_mFirstPadrow;   //!
   TBranch        *b_mMergedPairs_mLastPadrow;   //!
   TBranch        *b_mMergedPairs_mFirstFitPadrow;   //!
   TBranch        *b_mMergedPairs_mLastFitPadrow;   //!
   TBranch        *b_mMergedPairs_mFirstSector;   //!
   TBranch        *b_mMergedPairs_mLastSector;   //!
   TBranch        *b_mMergedPairs_mRecoKey;   //!
   TBranch        *b_mMergedPairs_mFitPts;   //!
   TBranch        *b_mMergedPairs_mFitSvt;   //!
   TBranch        *b_mMergedPairs_mFitSsd;   //!
   TBranch        *b_mMergedPairs_mFitFtpc;   //!
   TBranch        *b_mMergedPairs_mDedxPts;   //!
   TBranch        *b_mMergedPairs_mAllPts;   //!
   TBranch        *b_mMergedPairs_mCharge;   //!
   TBranch        *b_mMergedPairs_mNAssocMc;   //!
   TBranch        *b_mMergedPairs_mNPossible;   //!
   TBranch        *b_mMergedPairs_mIsValidPr;   //!
   TBranch        *b_mMergedPairs_mEmcTowerAdc;   //!
   TBranch        *b_mMergedPairs_mEmcEnergyRcHit;   //!
   TBranch        *b_mMergedPairs_mEmcSoftIdHiTowerRc;   //!
   TBranch        *b_mSplitPairs_;   //!
   TBranch        *b_mSplitPairs_mNCommonHit;   //!
   TBranch        *b_mSplitPairs_mIsBestContam;   //!
   TBranch        *b_mSplitPairs_mDominatrack;   //!
   TBranch        *b_mSplitPairs_mDominCommonHit;   //!
   TBranch        *b_mSplitPairs_mAvgQuality;   //!
   TBranch        *b_mSplitPairs_mIsValid;   //!
   TBranch        *b_mSplitPairs_mPtMc;   //!
   TBranch        *b_mSplitPairs_mPzMc;   //!
   TBranch        *b_mSplitPairs_mEtaMc;   //!
   TBranch        *b_mSplitPairs_mPhiMc;   //!
   TBranch        *b_mSplitPairs_mNHitMc;   //!
   TBranch        *b_mSplitPairs_mNSvtHitMc;   //!
   TBranch        *b_mSplitPairs_mNSsdHitMc;   //!
   TBranch        *b_mSplitPairs_mNFtpcHitMc;   //!
   TBranch        *b_mSplitPairs_mNBemcHitMc;   //!
   TBranch        *b_mSplitPairs_mNBprsHitMc;   //!
   TBranch        *b_mSplitPairs_mNBsmdeHitMc;   //!
   TBranch        *b_mSplitPairs_mNBsmdpHitMc;   //!
   TBranch        *b_mSplitPairs_mNEemcHitMc;   //!
   TBranch        *b_mSplitPairs_mNEprsHitMc;   //!
   TBranch        *b_mSplitPairs_mNEsmduHitMc;   //!
   TBranch        *b_mSplitPairs_mNEsmdvHitMc;   //!
   TBranch        *b_mSplitPairs_mGeantId;   //!
   TBranch        *b_mSplitPairs_mChargeMc;   //!
   TBranch        *b_mSplitPairs_mStopR;   //!
   TBranch        *b_mSplitPairs_mKey;   //!
   TBranch        *b_mSplitPairs_mParentKey;   //!
   TBranch        *b_mSplitPairs_mParentGeantId;   //!
   TBranch        *b_mSplitPairs_mEmcEnergyMcHit;   //!
   TBranch        *b_mSplitPairs_mEmcEnergyMcSum;   //!
   TBranch        *b_mSplitPairs_mEmcSoftIdHiTowerMc;   //!
   TBranch        *b_mSplitPairs_mNAssocGl;   //!
   TBranch        *b_mSplitPairs_mNAssocPr;   //!
   TBranch        *b_mSplitPairs_mIsPrimary;   //!
   TBranch        *b_mSplitPairs_fUniqueID;   //!
   TBranch        *b_mSplitPairs_fBits;   //!
   TBranch        *b_mSplitPairs_mIsValidGl;   //!
   TBranch        *b_mSplitPairs_mPtPr;   //!
   TBranch        *b_mSplitPairs_mPzPr;   //!
   TBranch        *b_mSplitPairs_mEtaPr;   //!
   TBranch        *b_mSplitPairs_mPhiPr;   //!
   TBranch        *b_mSplitPairs_mDcaPr;   //!
   TBranch        *b_mSplitPairs_mDcaXYPr;   //!
   TBranch        *b_mSplitPairs_mDcaZPr;   //!
   TBranch        *b_mSplitPairs_mDcaXYPrMcV;   //!
   TBranch        *b_mSplitPairs_mDcaZPrMcV;   //!
   TBranch        *b_mSplitPairs_mCurvPr;   //!
   TBranch        *b_mSplitPairs_mTanLPr;   //!
   TBranch        *b_mSplitPairs_mErrP;   //!
   TBranch        *b_mSplitPairs_mChi2Pr;   //!
   TBranch        *b_mSplitPairs_mFlag;   //!
   TBranch        *b_mSplitPairs_mDedx;   //!
   TBranch        *b_mSplitPairs_mPtGl;   //!
   TBranch        *b_mSplitPairs_mPzGl;   //!
   TBranch        *b_mSplitPairs_mEtaGl;   //!
   TBranch        *b_mSplitPairs_mPhiGl;   //!
   TBranch        *b_mSplitPairs_mDcaGl;   //!
   TBranch        *b_mSplitPairs_mDcaXYGl;   //!
   TBranch        *b_mSplitPairs_mDcaZGl;   //!
   TBranch        *b_mSplitPairs_mDcaXYGlMcV;   //!
   TBranch        *b_mSplitPairs_mDcaZGlMcV;   //!
   TBranch        *b_mSplitPairs_mCurvGl;   //!
   TBranch        *b_mSplitPairs_mTanLGl;   //!
   TBranch        *b_mSplitPairs_mErrG;   //!
   TBranch        *b_mSplitPairs_mSeedQA;   //!
   TBranch        *b_mSplitPairs_mPidPion;   //!
   TBranch        *b_mSplitPairs_mPidProton;   //!
   TBranch        *b_mSplitPairs_mPidKaon;   //!
   TBranch        *b_mSplitPairs_mPidElectron;   //!
   TBranch        *b_mSplitPairs_mFirstZ;   //!
   TBranch        *b_mSplitPairs_mLastZ;   //!
   TBranch        *b_mSplitPairs_mFirstPadrow;   //!
   TBranch        *b_mSplitPairs_mLastPadrow;   //!
   TBranch        *b_mSplitPairs_mFirstFitPadrow;   //!
   TBranch        *b_mSplitPairs_mLastFitPadrow;   //!
   TBranch        *b_mSplitPairs_mFirstSector;   //!
   TBranch        *b_mSplitPairs_mLastSector;   //!
   TBranch        *b_mSplitPairs_mRecoKey;   //!
   TBranch        *b_mSplitPairs_mFitPts;   //!
   TBranch        *b_mSplitPairs_mFitSvt;   //!
   TBranch        *b_mSplitPairs_mFitSsd;   //!
   TBranch        *b_mSplitPairs_mFitFtpc;   //!
   TBranch        *b_mSplitPairs_mDedxPts;   //!
   TBranch        *b_mSplitPairs_mAllPts;   //!
   TBranch        *b_mSplitPairs_mCharge;   //!
   TBranch        *b_mSplitPairs_mNAssocMc;   //!
   TBranch        *b_mSplitPairs_mNPossible;   //!
   TBranch        *b_mSplitPairs_mIsValidPr;   //!
   TBranch        *b_mSplitPairs_mEmcTowerAdc;   //!
   TBranch        *b_mSplitPairs_mEmcEnergyRcHit;   //!
   TBranch        *b_mSplitPairs_mEmcSoftIdHiTowerRc;   //!
   TBranch        *b_mGhostPairs_;   //!
   TBranch        *b_mGhostPairs_mNCommonHit;   //!
   TBranch        *b_mGhostPairs_mIsBestContam;   //!
   TBranch        *b_mGhostPairs_mDominatrack;   //!
   TBranch        *b_mGhostPairs_mDominCommonHit;   //!
   TBranch        *b_mGhostPairs_mAvgQuality;   //!
   TBranch        *b_mGhostPairs_mIsValid;   //!
   TBranch        *b_mGhostPairs_mPtMc;   //!
   TBranch        *b_mGhostPairs_mPzMc;   //!
   TBranch        *b_mGhostPairs_mEtaMc;   //!
   TBranch        *b_mGhostPairs_mPhiMc;   //!
   TBranch        *b_mGhostPairs_mNHitMc;   //!
   TBranch        *b_mGhostPairs_mNSvtHitMc;   //!
   TBranch        *b_mGhostPairs_mNSsdHitMc;   //!
   TBranch        *b_mGhostPairs_mNFtpcHitMc;   //!
   TBranch        *b_mGhostPairs_mNBemcHitMc;   //!
   TBranch        *b_mGhostPairs_mNBprsHitMc;   //!
   TBranch        *b_mGhostPairs_mNBsmdeHitMc;   //!
   TBranch        *b_mGhostPairs_mNBsmdpHitMc;   //!
   TBranch        *b_mGhostPairs_mNEemcHitMc;   //!
   TBranch        *b_mGhostPairs_mNEprsHitMc;   //!
   TBranch        *b_mGhostPairs_mNEsmduHitMc;   //!
   TBranch        *b_mGhostPairs_mNEsmdvHitMc;   //!
   TBranch        *b_mGhostPairs_mGeantId;   //!
   TBranch        *b_mGhostPairs_mChargeMc;   //!
   TBranch        *b_mGhostPairs_mStopR;   //!
   TBranch        *b_mGhostPairs_mKey;   //!
   TBranch        *b_mGhostPairs_mParentKey;   //!
   TBranch        *b_mGhostPairs_mParentGeantId;   //!
   TBranch        *b_mGhostPairs_mEmcEnergyMcHit;   //!
   TBranch        *b_mGhostPairs_mEmcEnergyMcSum;   //!
   TBranch        *b_mGhostPairs_mEmcSoftIdHiTowerMc;   //!
   TBranch        *b_mGhostPairs_mNAssocGl;   //!
   TBranch        *b_mGhostPairs_mNAssocPr;   //!
   TBranch        *b_mGhostPairs_mIsPrimary;   //!
   TBranch        *b_mGhostPairs_fUniqueID;   //!
   TBranch        *b_mGhostPairs_fBits;   //!
   TBranch        *b_mGhostPairs_mIsValidGl;   //!
   TBranch        *b_mGhostPairs_mPtPr;   //!
   TBranch        *b_mGhostPairs_mPzPr;   //!
   TBranch        *b_mGhostPairs_mEtaPr;   //!
   TBranch        *b_mGhostPairs_mPhiPr;   //!
   TBranch        *b_mGhostPairs_mDcaPr;   //!
   TBranch        *b_mGhostPairs_mDcaXYPr;   //!
   TBranch        *b_mGhostPairs_mDcaZPr;   //!
   TBranch        *b_mGhostPairs_mDcaXYPrMcV;   //!
   TBranch        *b_mGhostPairs_mDcaZPrMcV;   //!
   TBranch        *b_mGhostPairs_mCurvPr;   //!
   TBranch        *b_mGhostPairs_mTanLPr;   //!
   TBranch        *b_mGhostPairs_mErrP;   //!
   TBranch        *b_mGhostPairs_mChi2Pr;   //!
   TBranch        *b_mGhostPairs_mFlag;   //!
   TBranch        *b_mGhostPairs_mDedx;   //!
   TBranch        *b_mGhostPairs_mPtGl;   //!
   TBranch        *b_mGhostPairs_mPzGl;   //!
   TBranch        *b_mGhostPairs_mEtaGl;   //!
   TBranch        *b_mGhostPairs_mPhiGl;   //!
   TBranch        *b_mGhostPairs_mDcaGl;   //!
   TBranch        *b_mGhostPairs_mDcaXYGl;   //!
   TBranch        *b_mGhostPairs_mDcaZGl;   //!
   TBranch        *b_mGhostPairs_mDcaXYGlMcV;   //!
   TBranch        *b_mGhostPairs_mDcaZGlMcV;   //!
   TBranch        *b_mGhostPairs_mCurvGl;   //!
   TBranch        *b_mGhostPairs_mTanLGl;   //!
   TBranch        *b_mGhostPairs_mErrG;   //!
   TBranch        *b_mGhostPairs_mSeedQA;   //!
   TBranch        *b_mGhostPairs_mPidPion;   //!
   TBranch        *b_mGhostPairs_mPidProton;   //!
   TBranch        *b_mGhostPairs_mPidKaon;   //!
   TBranch        *b_mGhostPairs_mPidElectron;   //!
   TBranch        *b_mGhostPairs_mFirstZ;   //!
   TBranch        *b_mGhostPairs_mLastZ;   //!
   TBranch        *b_mGhostPairs_mFirstPadrow;   //!
   TBranch        *b_mGhostPairs_mLastPadrow;   //!
   TBranch        *b_mGhostPairs_mFirstFitPadrow;   //!
   TBranch        *b_mGhostPairs_mLastFitPadrow;   //!
   TBranch        *b_mGhostPairs_mFirstSector;   //!
   TBranch        *b_mGhostPairs_mLastSector;   //!
   TBranch        *b_mGhostPairs_mRecoKey;   //!
   TBranch        *b_mGhostPairs_mFitPts;   //!
   TBranch        *b_mGhostPairs_mFitSvt;   //!
   TBranch        *b_mGhostPairs_mFitSsd;   //!
   TBranch        *b_mGhostPairs_mFitFtpc;   //!
   TBranch        *b_mGhostPairs_mDedxPts;   //!
   TBranch        *b_mGhostPairs_mAllPts;   //!
   TBranch        *b_mGhostPairs_mCharge;   //!
   TBranch        *b_mGhostPairs_mNAssocMc;   //!
   TBranch        *b_mGhostPairs_mNPossible;   //!
   TBranch        *b_mGhostPairs_mIsValidPr;   //!
   TBranch        *b_mGhostPairs_mEmcTowerAdc;   //!
   TBranch        *b_mGhostPairs_mEmcEnergyRcHit;   //!
   TBranch        *b_mGhostPairs_mEmcSoftIdHiTowerRc;   //!
   TBranch        *b_mContamPairs_;   //!
   TBranch        *b_mContamPairs_mParentGeantId;   //!
   TBranch        *b_mContamPairs_mGeantProcess;   //!
   TBranch        *b_mContamPairs_mPtMcParent;   //!
   TBranch        *b_mContamPairs_mEtaMcParent;   //!
   TBranch        *b_mContamPairs_mParentParentGeantId;   //!
   TBranch        *b_mContamPairs_mPtMcParentParent;   //!
   TBranch        *b_mContamPairs_mStartX;   //!
   TBranch        *b_mContamPairs_mStartY;   //!
   TBranch        *b_mContamPairs_mStartZ;   //!
   TBranch        *b_mContamPairs_mNCommonHit;   //!
   TBranch        *b_mContamPairs_mIsBestContam;   //!
   TBranch        *b_mContamPairs_mDominatrack;   //!
   TBranch        *b_mContamPairs_mDominCommonHit;   //!
   TBranch        *b_mContamPairs_mAvgQuality;   //!
   TBranch        *b_mContamPairs_mIsValid;   //!
   TBranch        *b_mContamPairs_mPtMc;   //!
   TBranch        *b_mContamPairs_mPzMc;   //!
   TBranch        *b_mContamPairs_mEtaMc;   //!
   TBranch        *b_mContamPairs_mPhiMc;   //!
   TBranch        *b_mContamPairs_mNHitMc;   //!
   TBranch        *b_mContamPairs_mNSvtHitMc;   //!
   TBranch        *b_mContamPairs_mNSsdHitMc;   //!
   TBranch        *b_mContamPairs_mNFtpcHitMc;   //!
   TBranch        *b_mContamPairs_mNBemcHitMc;   //!
   TBranch        *b_mContamPairs_mNBprsHitMc;   //!
   TBranch        *b_mContamPairs_mNBsmdeHitMc;   //!
   TBranch        *b_mContamPairs_mNBsmdpHitMc;   //!
   TBranch        *b_mContamPairs_mNEemcHitMc;   //!
   TBranch        *b_mContamPairs_mNEprsHitMc;   //!
   TBranch        *b_mContamPairs_mNEsmduHitMc;   //!
   TBranch        *b_mContamPairs_mNEsmdvHitMc;   //!
   TBranch        *b_mContamPairs_mGeantId;   //!
   TBranch        *b_mContamPairs_mChargeMc;   //!
   TBranch        *b_mContamPairs_mStopR;   //!
   TBranch        *b_mContamPairs_mKey;   //!
   TBranch        *b_mContamPairs_mParentKey;   //!
   //TBranch        *b_mContamPairs_mParentGeantId;   //!
   TBranch        *b_mContamPairs_mEmcEnergyMcHit;   //!
   TBranch        *b_mContamPairs_mEmcEnergyMcSum;   //!
   TBranch        *b_mContamPairs_mEmcSoftIdHiTowerMc;   //!
   TBranch        *b_mContamPairs_mNAssocGl;   //!
   TBranch        *b_mContamPairs_mNAssocPr;   //!
   TBranch        *b_mContamPairs_mIsPrimary;   //!
   TBranch        *b_mContamPairs_fUniqueID;   //!
   TBranch        *b_mContamPairs_fBits;   //!
   TBranch        *b_mContamPairs_mIsValidGl;   //!
   TBranch        *b_mContamPairs_mPtPr;   //!
   TBranch        *b_mContamPairs_mPzPr;   //!
   TBranch        *b_mContamPairs_mEtaPr;   //!
   TBranch        *b_mContamPairs_mPhiPr;   //!
   TBranch        *b_mContamPairs_mDcaPr;   //!
   TBranch        *b_mContamPairs_mDcaXYPr;   //!
   TBranch        *b_mContamPairs_mDcaZPr;   //!
   TBranch        *b_mContamPairs_mDcaXYPrMcV;   //!
   TBranch        *b_mContamPairs_mDcaZPrMcV;   //!
   TBranch        *b_mContamPairs_mCurvPr;   //!
   TBranch        *b_mContamPairs_mTanLPr;   //!
   TBranch        *b_mContamPairs_mErrP;   //!
   TBranch        *b_mContamPairs_mChi2Pr;   //!
   TBranch        *b_mContamPairs_mFlag;   //!
   TBranch        *b_mContamPairs_mDedx;   //!
   TBranch        *b_mContamPairs_mPtGl;   //!
   TBranch        *b_mContamPairs_mPzGl;   //!
   TBranch        *b_mContamPairs_mEtaGl;   //!
   TBranch        *b_mContamPairs_mPhiGl;   //!
   TBranch        *b_mContamPairs_mDcaGl;   //!
   TBranch        *b_mContamPairs_mDcaXYGl;   //!
   TBranch        *b_mContamPairs_mDcaZGl;   //!
   TBranch        *b_mContamPairs_mDcaXYGlMcV;   //!
   TBranch        *b_mContamPairs_mDcaZGlMcV;   //!
   TBranch        *b_mContamPairs_mCurvGl;   //!
   TBranch        *b_mContamPairs_mTanLGl;   //!
   TBranch        *b_mContamPairs_mErrG;   //!
   TBranch        *b_mContamPairs_mSeedQA;   //!
   TBranch        *b_mContamPairs_mPidPion;   //!
   TBranch        *b_mContamPairs_mPidProton;   //!
   TBranch        *b_mContamPairs_mPidKaon;   //!
   TBranch        *b_mContamPairs_mPidElectron;   //!
   TBranch        *b_mContamPairs_mFirstZ;   //!
   TBranch        *b_mContamPairs_mLastZ;   //!
   TBranch        *b_mContamPairs_mFirstPadrow;   //!
   TBranch        *b_mContamPairs_mLastPadrow;   //!
   TBranch        *b_mContamPairs_mFirstFitPadrow;   //!
   TBranch        *b_mContamPairs_mLastFitPadrow;   //!
   TBranch        *b_mContamPairs_mFirstSector;   //!
   TBranch        *b_mContamPairs_mLastSector;   //!
   TBranch        *b_mContamPairs_mRecoKey;   //!
   TBranch        *b_mContamPairs_mFitPts;   //!
   TBranch        *b_mContamPairs_mFitSvt;   //!
   TBranch        *b_mContamPairs_mFitSsd;   //!
   TBranch        *b_mContamPairs_mFitFtpc;   //!
   TBranch        *b_mContamPairs_mDedxPts;   //!
   TBranch        *b_mContamPairs_mAllPts;   //!
   TBranch        *b_mContamPairs_mCharge;   //!
   TBranch        *b_mContamPairs_mNAssocMc;   //!
   TBranch        *b_mContamPairs_mNPossible;   //!
   TBranch        *b_mContamPairs_mIsValidPr;   //!
   TBranch        *b_mContamPairs_mEmcTowerAdc;   //!
   TBranch        *b_mContamPairs_mEmcEnergyRcHit;   //!
   TBranch        *b_mContamPairs_mEmcSoftIdHiTowerRc;   //!
   TBranch        *b_mMatGlobPairs_;   //!
   TBranch        *b_mMatGlobPairs_mNCommonHit;   //!
   TBranch        *b_mMatGlobPairs_mIsBestContam;   //!
   TBranch        *b_mMatGlobPairs_mDominatrack;   //!
   TBranch        *b_mMatGlobPairs_mDominCommonHit;   //!
   TBranch        *b_mMatGlobPairs_mAvgQuality;   //!
   TBranch        *b_mMatGlobPairs_mIsValid;   //!
   TBranch        *b_mMatGlobPairs_mPtMc;   //!
   TBranch        *b_mMatGlobPairs_mPzMc;   //!
   TBranch        *b_mMatGlobPairs_mEtaMc;   //!
   TBranch        *b_mMatGlobPairs_mPhiMc;   //!
   TBranch        *b_mMatGlobPairs_mNHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNSvtHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNSsdHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNFtpcHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNBemcHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNBprsHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNBsmdeHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNBsmdpHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNEemcHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNEprsHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNEsmduHitMc;   //!
   TBranch        *b_mMatGlobPairs_mNEsmdvHitMc;   //!
   TBranch        *b_mMatGlobPairs_mGeantId;   //!
   TBranch        *b_mMatGlobPairs_mChargeMc;   //!
   TBranch        *b_mMatGlobPairs_mStopR;   //!
   TBranch        *b_mMatGlobPairs_mKey;   //!
   TBranch        *b_mMatGlobPairs_mParentKey;   //!
   TBranch        *b_mMatGlobPairs_mParentGeantId;   //!
   TBranch        *b_mMatGlobPairs_mEmcEnergyMcHit;   //!
   TBranch        *b_mMatGlobPairs_mEmcEnergyMcSum;   //!
   TBranch        *b_mMatGlobPairs_mEmcSoftIdHiTowerMc;   //!
   TBranch        *b_mMatGlobPairs_mNAssocGl;   //!
   TBranch        *b_mMatGlobPairs_mNAssocPr;   //!
   TBranch        *b_mMatGlobPairs_mIsPrimary;   //!
   TBranch        *b_mMatGlobPairs_fUniqueID;   //!
   TBranch        *b_mMatGlobPairs_fBits;   //!
   TBranch        *b_mMatGlobPairs_mIsValidGl;   //!
   TBranch        *b_mMatGlobPairs_mPtPr;   //!
   TBranch        *b_mMatGlobPairs_mPzPr;   //!
   TBranch        *b_mMatGlobPairs_mEtaPr;   //!
   TBranch        *b_mMatGlobPairs_mPhiPr;   //!
   TBranch        *b_mMatGlobPairs_mDcaPr;   //!
   TBranch        *b_mMatGlobPairs_mDcaXYPr;   //!
   TBranch        *b_mMatGlobPairs_mDcaZPr;   //!
   TBranch        *b_mMatGlobPairs_mDcaXYPrMcV;   //!
   TBranch        *b_mMatGlobPairs_mDcaZPrMcV;   //!
   TBranch        *b_mMatGlobPairs_mCurvPr;   //!
   TBranch        *b_mMatGlobPairs_mTanLPr;   //!
   TBranch        *b_mMatGlobPairs_mErrP;   //!
   TBranch        *b_mMatGlobPairs_mChi2Pr;   //!
   TBranch        *b_mMatGlobPairs_mFlag;   //!
   TBranch        *b_mMatGlobPairs_mDedx;   //!
   TBranch        *b_mMatGlobPairs_mPtGl;   //!
   TBranch        *b_mMatGlobPairs_mPzGl;   //!
   TBranch        *b_mMatGlobPairs_mEtaGl;   //!
   TBranch        *b_mMatGlobPairs_mPhiGl;   //!
   TBranch        *b_mMatGlobPairs_mDcaGl;   //!
   TBranch        *b_mMatGlobPairs_mDcaXYGl;   //!
   TBranch        *b_mMatGlobPairs_mDcaZGl;   //!
   TBranch        *b_mMatGlobPairs_mDcaXYGlMcV;   //!
   TBranch        *b_mMatGlobPairs_mDcaZGlMcV;   //!
   TBranch        *b_mMatGlobPairs_mCurvGl;   //!
   TBranch        *b_mMatGlobPairs_mTanLGl;   //!
   TBranch        *b_mMatGlobPairs_mErrG;   //!
   TBranch        *b_mMatGlobPairs_mSeedQA;   //!
   TBranch        *b_mMatGlobPairs_mPidPion;   //!
   TBranch        *b_mMatGlobPairs_mPidProton;   //!
   TBranch        *b_mMatGlobPairs_mPidKaon;   //!
   TBranch        *b_mMatGlobPairs_mPidElectron;   //!
   TBranch        *b_mMatGlobPairs_mFirstZ;   //!
   TBranch        *b_mMatGlobPairs_mLastZ;   //!
   TBranch        *b_mMatGlobPairs_mFirstPadrow;   //!
   TBranch        *b_mMatGlobPairs_mLastPadrow;   //!
   TBranch        *b_mMatGlobPairs_mFirstFitPadrow;   //!
   TBranch        *b_mMatGlobPairs_mLastFitPadrow;   //!
   TBranch        *b_mMatGlobPairs_mFirstSector;   //!
   TBranch        *b_mMatGlobPairs_mLastSector;   //!
   TBranch        *b_mMatGlobPairs_mRecoKey;   //!
   TBranch        *b_mMatGlobPairs_mFitPts;   //!
   TBranch        *b_mMatGlobPairs_mFitSvt;   //!
   TBranch        *b_mMatGlobPairs_mFitSsd;   //!
   TBranch        *b_mMatGlobPairs_mFitFtpc;   //!
   TBranch        *b_mMatGlobPairs_mDedxPts;   //!
   TBranch        *b_mMatGlobPairs_mAllPts;   //!
   TBranch        *b_mMatGlobPairs_mCharge;   //!
   TBranch        *b_mMatGlobPairs_mNAssocMc;   //!
   TBranch        *b_mMatGlobPairs_mNPossible;   //!
   TBranch        *b_mMatGlobPairs_mIsValidPr;   //!
   TBranch        *b_mMatGlobPairs_mEmcTowerAdc;   //!
   TBranch        *b_mMatGlobPairs_mEmcEnergyRcHit;   //!
   TBranch        *b_mMatGlobPairs_mEmcSoftIdHiTowerRc;   //!
   TBranch        *b_StMiniMcEvent_fUniqueID;   //!
   TBranch        *b_StMiniMcEvent_fBits;   //!

   StMiniMcTree(TString listfile, TTree *tree=0);
   virtual ~StMiniMcTree();
   virtual Int_t    Cut(Long64_t entry);
   virtual Int_t    GetEntry(Long64_t entry);
   virtual Long64_t LoadTree(Long64_t entry);
   virtual void     Init(TTree *tree);
   virtual void     Loop(Long64_t nentries, TString outdir, TString particle, Int_t energy);
   virtual Bool_t   Notify();
   virtual void     Show(Long64_t entry = -1);

   ClassDef(StMiniMcTree,0)
};

#endif
